spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spacial?serverTimezone=Asia/Seoul&CharacterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    username: owo
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true